CREATE TABLE npi (
  npi               bigint PRIMARY KEY,
  entity_type_code  smallint,
  replacement_npi   bigint,
  employer_ein      varchar(9),
  provider_organization_name varchar(70),
  provider_last_name varchar(35),
  provider_first_name varchar(20),
  provider_middle_name varchar(20),
  provider_name_prefix_text varchar(5),
  provider_name_suffix_text varchar(5),
  provider_credential_text varchar(20),
  provider_other_organization_name varchar(70),
  provider_other_organization_name_type_code varchar(1),
  provider_other_last_name varchar(35),
  provider_other_first_name varchar(20),
  provider_other_middle_name varchar(20),
  provider_other_name_prefix_text varchar(5),
  provider_other_name_suffix_text varchar(5),
  provider_other_credential_text varchar(20),
  provider_other_last_name_type_code smallint,
  provider_first_line_business_mailing_address varchar(55),
  provider_second
);