---
# file: roles/db/tasks/main.yml
- name: be sure postgres apt key installed
  apt_key: id=ACCC4CF8 url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
- name: be sure postgres repository installed
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"
- name: be sure python setup tools/ postgreSQL are installed
  apt: update_cache=yes pkg={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-dev
    - postgresql-9.2
    - postgresql-server-dev-9.2
- name: be sure postgreSQL python package is installed
  easy_install: name=psycopg2
- name: be sure system allows enough shared memory
  template: src=sysctl.conf dest=/etc/sysctl.conf owner=root group=root mode=644
  register: result
- name: be sure sysctl changes are applied
  shell: sysctl -p
  when_changed: $result
- name: be sure postgres is configured
  template: src=postgresql.conf dest=/etc/postgresql/9.2/main/postgresql.conf owner=postgres group=postgres mode=644
  notify: 
    - restart postgres
- name: be sure postgres user config present
  copy: src={{ item }} dest=/etc/postgresql/9.2/main/{{ item }} owner=postgres group=postgres mode=644
  with_items:
    - pg_hba.conf
    - pg_ident.conf
  register: result
- name: if configuration changed, restart postgres
  service: name=postgresql state=restarted
  when_changed: $result
- name: be sure postgres user is setup
  sudo: no
  postgresql_user: login_user=postgres name=postgres password={{ postgres_password }}
